name: CI/CD - InfoMundi

on:
  push:
    branches: [ "main" ]

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-tests
    services:
      docker:
        image: docker:20.10-dind
        privileged: true

    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/infomundi:latest

      - name: Set up Docker Compose for staging
        run: |
          docker compose -f .github/compose.staging.yml up -d --build

      - name: Wait for API to be healthy
        run: |
          for i in {1..20}; do
            curl -fs http://localhost:8000/api/cleaned_data && exit 0
            echo "API not ready yet... retrying"
            sleep 5
          done
          exit 1

      - name: Run integration tests
        run: |
          curl -f http://localhost:8000/api/cleaned_data
          curl -f http://localhost:8000/docs
