name: CI/CD – InfoMundi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint-and-tests:
    name: Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Lint
        run: |
          pip install flake8
          # No fallar la build por warnings de estilo en esta demo
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

  build-image:
    name: Build Docker image (no push)
    runs-on: ubuntu-latest
    needs: lint-and-tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # No login (evitamos condicionales con secrets)
      # Si luego quieres pushear, vuelve a activar el login y el push abajo.

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: infomundi:ci-${{ github.sha }}
